[package]
name = "katcp_canonicalizer"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
clap = { version = "3", features = ["derive"] }
tokio = { version = "1", features = ["full"]}
